### ISSUE TITLE
IllegalStateException when player completed.

### ISSUE THREAD

**Issue by PaulWoitaschek** [AntennaPod/AntennaPod-AudioPlayer#5] opened 2016-01-07 09:21 UTC
> java.lang.IllegalStateException: start failed
                               at android.media.MediaCodec.start(Native Method)
                               at org.antennapod.audio.SonicAudioPlayer$2.run(SonicAudioPlayer.java:598)
                               at java.lang.Thread.run(Thread.java:841)

After the player hit completion a call to `start()` results in an `IllegalStateException`. For `android.media.MediaPlayer` calling start at that point results in the playback being started from 0.

To reproduce (pseudo code)

```java
// create player
player.setDataSource(...)
player.prepare()
player.start()
Thread.sleep(...) // wait for playback to end
player.start()
// boom
```

**Comment by mfietz** [comment] 2016-01-07 23:43
Actually, I think this might be working as intended. Just like some AudioTrack methods can only be called in certain states, some of Sonic's methods should only be called in the appropriate state, as well.

So, after completion you have to call ``reset()`` and ``setDataSource(...)`` to be in the appropriate state to call ``start()`` without an exception.

Inclined to calling this a wontfix.

**Comment by PaulWoitaschek** [comment] 2016-01-08 08:19
Your MediaPlayer class acts as a delegate to the Android and the Sonic Media Player implementation. 
Because of that I would make sure that it behaves the same - no matter what the underlying implementation looks like. Else you land in a situation where you make changes in using the class and it works on some devices and crashes on others. That's a disaster.

I am not in range of a machine right now but I think a call to initStream() should fix that.

**Comment by mfietz** [comment] 2016-01-08 11:27
Resolved by https://github.com/AntennaPod/AntennaPod-AudioPlayer/commit/4e782cfe402825d0b36709398239fd75673af5e0

**Closed by mfietz** 2016-01-08 11:27 UTC
